### ISSUE TITLE
Evaluate internal audit feedback for Merkledrop contract

### ISSUE THREAD

**Issue by weilbith** [trustlines-protocol/merkle-drop#46]
- talk about it
- plan next steps
- define to do changes

**Comment by berndbohmeier** [comment]
- I would then use 
`event Withdraw(address recipient, uint value, uint originalValue);`
where `value = valueToSend`
- Lets follow a normal ERC20 Token Interface and add the burn method. 

I would add that according to the ERC Standard we should do
`require(token.transfer(...))` because according to the standard this does not necessarily fail with a exception but can also just return false.

**Comment by cducrest** [comment]
The finding 1 of Yoichi has been fixed. 
The tool for coputing the Merkle root already checks that not two addresses are equal.
I will fix the other small changes.
